spring:
  datasource:
    username: root
    password: 1231
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_sys?useUnicode=yes&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource