spring:
  datasource:
    username: root
    password: 1231
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_sys?useUnicode=yes&characterEncoding=UTF-8
  jooq:
    sql-dialect: mysql_8_0
  flyway:
    enabled: false
  redis:
    password: a4dc069cfe33f7622830fc759741f9e2
    host: 139.199.104.252
  application:
    name: auth-system
server:
  port: 9001
